import { useState, useEffect } from 'react'
import { healthAPI } from '../api'

export default function Insights() {
  const [insights, setInsights] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [days, setDays] = useState(7)
  const [ollamaStatus, setOllamaStatus] = useState(null)

  useEffect(() => {
    checkOllamaStatus()
  }, [])

  const checkOllamaStatus = async () => {
    try {
      const response = await healthAPI.checkHealth()
      setOllamaStatus(response.data.ollama)
    } catch (error) {
      console.error('Error checking Ollama status:', error)
      setOllamaStatus('disconnected')
    }
  }

  const generateInsights = async () => {
    try {
      setLoading(true)
      setError(null)
      const response = await healthAPI.generateInsights(days)
      setInsights(response.data)
    } catch (error) {
      console.error('Error generating insights:', error)
      setError(error.response?.data?.detail || 'Failed to generate insights. Please ensure you have uploaded data and Ollama is running.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">AI Insights</h1>
          <p className="text-sm text-gray-600 mt-1">
            Neutral, trend-based observations generated by local LLM
          </p>
        </div>
        <div className={`px-3 py-1 rounded-full text-sm ${
          ollamaStatus === 'connected' 
            ? 'bg-green-100 text-green-800' 
            : 'bg-red-100 text-red-800'
        }`}>
          Ollama: {ollamaStatus || 'checking...'}
        </div>
      </div>

      {/* Generate Insights Section */}
      <div className="bg-white rounded-lg shadow p-6">
        <h2 className="text-lg font-semibold mb-4">Generate New Insights</h2>
        <div className="flex items-center space-x-4">
          <div className="flex space-x-2">
            <label className="text-sm text-gray-600">Time period:</label>
            {[7, 14, 30].map(d => (
              <button
                key={d}
                onClick={() => setDays(d)}
                className={`px-3 py-1 rounded text-sm transition ${
                  days === d
                    ? 'bg-blue-600 text-white'
                    : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                }`}
              >
                {d} days
              </button>
            ))}
          </div>
          <button
            onClick={generateInsights}
            disabled={loading || ollamaStatus !== 'connected'}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition disabled:bg-gray-400 disabled:cursor-not-allowed"
          >
            {loading ? 'Generating...' : 'Generate Insights'}
          </button>
        </div>
        {ollamaStatus !== 'connected' && (
          <div className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <p className="text-yellow-900 text-sm">
              ⚠️ Ollama is not connected. Please ensure Ollama is running locally.
            </p>
            <p className="text-yellow-800 text-xs mt-1">
              Start Ollama with: <code className="bg-yellow-100 px-1 rounded">ollama serve</code>
            </p>
          </div>
        )}
      </div>

      {/* Error Display */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <p className="text-red-900 font-medium">Error</p>
          <p className="text-red-700 text-sm mt-1">{error}</p>
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div className="bg-white rounded-lg shadow p-12 text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4"></div>
          <p className="text-gray-600">Analyzing your health data...</p>
          <p className="text-sm text-gray-500 mt-2">This may take 30-60 seconds</p>
        </div>
      )}

      {/* Insights Display */}
      {insights && !loading && (
        <div className="space-y-6">
          {/* Summary */}
          <div className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg shadow p-6 border border-blue-100">
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Summary</h2>
            <p className="text-gray-700 leading-relaxed">{insights.summary}</p>
            <div className="mt-4 flex items-center text-xs text-gray-500">
              <span>Generated: {new Date(insights.generated_at).toLocaleString()}</span>
              <span className="mx-2">•</span>
              <span>Model: {insights.model}</span>
            </div>
          </div>

          {/* Detailed Insights */}
          {insights.insights && insights.insights.length > 0 && (
            <div className="space-y-4">
              <h2 className="text-lg font-semibold text-gray-900">Detailed Observations</h2>
              {insights.insights.map((insight, idx) => (
                <div key={idx} className="bg-white rounded-lg shadow p-6 border-l-4 border-blue-600">
                  <div className="flex items-start space-x-3">
                    <div className="flex-shrink-0 w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 font-semibold text-sm">
                      {idx + 1}
                    </div>
                    <div className="flex-1">
                      <div className="text-xs text-gray-500 uppercase tracking-wide mb-2">
                        {insight.category.replace(/_/g, ' ')}
                      </div>
                      <p className="text-gray-700 leading-relaxed">{insight.observation}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Context Data Used */}
          {insights.context && (
            <div className="bg-white rounded-lg shadow p-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Data Context</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Sleep Context */}
                {insights.context.sleep_summary && (
                  <div>
                    <h3 className="text-sm font-semibold text-gray-700 mb-2">Sleep Data</h3>
                    <div className="space-y-1 text-sm">
                      {insights.context.sleep_summary.last_night && (
                        <>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Last night:</span>
                            <span className="font-medium">
                              {insights.context.sleep_summary.last_night.time_asleep_hours}h
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">REM:</span>
                            <span className="font-medium text-purple-600">
                              {insights.context.sleep_summary.last_night.rem_percentage}%
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Deep:</span>
                            <span className="font-medium text-blue-600">
                              {insights.context.sleep_summary.last_night.deep_percentage}%
                            </span>
                          </div>
                        </>
                      )}
                    </div>
                  </div>
                )}

                {/* Activity Context */}
                {insights.context.activity_summary && (
                  <div>
                    <h3 className="text-sm font-semibold text-gray-700 mb-2">Activity Data</h3>
                    <div className="space-y-1 text-sm">
                      {insights.context.activity_summary.yesterday && (
                        <>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Steps:</span>
                            <span className="font-medium">
                              {insights.context.activity_summary.yesterday.steps.toLocaleString()}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Calories:</span>
                            <span className="font-medium text-orange-600">
                              {insights.context.activity_summary.yesterday.move_calories}
                            </span>
                          </div>
                        </>
                      )}
                    </div>
                  </div>
                )}
              </div>

              {/* Notable Patterns */}
              {insights.context.notable_patterns && insights.context.notable_patterns.length > 0 && (
                <div className="mt-4">
                  <h3 className="text-sm font-semibold text-gray-700 mb-2">Notable Patterns Detected</h3>
                  <ul className="space-y-1 text-sm text-gray-600">
                    {insights.context.notable_patterns.map((pattern, idx) => (
                      <li key={idx} className="flex items-start">
                        <span className="text-blue-600 mr-2">•</span>
                        <span>{pattern}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {/* Disclaimer */}
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
            <p className="text-xs text-gray-600">
              <strong>Note:</strong> These insights are generated by a local AI model for informational purposes only. 
              They represent neutral observations about data patterns and trends, not medical advice or diagnosis. 
              Consult healthcare professionals for medical guidance.
            </p>
          </div>
        </div>
      )}

      {/* Empty State */}
      {!insights && !loading && !error && (
        <div className="bg-white rounded-lg shadow p-12 text-center">
          <div className="text-6xl mb-4">🤖</div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Ready to Generate Insights</h3>
          <p className="text-gray-600 mb-6">
            Click "Generate Insights" to analyze your health data patterns using local AI
          </p>
          <div className="text-sm text-gray-500">
            <p>Insights are generated using Ollama running locally on your machine</p>
            <p>No data is sent to external services</p>
          </div>
        </div>
      )}
    </div>
  )
}
